set -u
DB=/home/azureuser/trading_corp/data/trading_corp.db
RO="sqlite3 -readonly $DB"
JW="json_extract(extra_json,'\$.whale_wallet')"
JN="json_extract(extra_json,'\$.whale_user_name')"
EP="entry_ts>='2026-05-21T12:28:07'"
R="('0x7714c16f86bcfdba47bfcb161dc39a2a1ff2b814','0x97ead83eb0e6b7f142e63284791882f05ddf3363','0x1f9f03e7ce52979b658b0bb75b483ff923fda025','0xf192501abae4c453cc15ddbe9543ed11e99a6ee2','0x27d2812fa0d04ca1b874cffedff7a15beb4ab0f8','0x4a1b8e8d38aecdc9687bb0f601801d59fa44724f','0xb56db5215443706244b0af76b3daaad3066ad621')"
echo "=== NOW ===" && $RO "SELECT datetime('now');"
echo "=== C1 our-copied per-whale post-epoch: fills|mkts|our_pnl|last_copy|days_ago|avgpx|sub70 ==="
$RO "SELECT $JN||'|'||COUNT(*)||'|'||COUNT(DISTINCT condition_id)||'|'||ROUND(SUM(realized_pnl),2)||'|'||substr(MAX(entry_ts),1,10)||'|'||CAST(julianday('now')-julianday(MAX(entry_ts)) AS INT)||'|'||ROUND(AVG(entry_price),3)||'|'||ROUND(1.0*SUM(CASE WHEN entry_price<0.70 THEN 1 ELSE 0 END)/COUNT(*),2) FROM polymarket_round_trips WHERE division='polymarket_copy_trading' AND $EP AND $JW IN $R GROUP BY $JN ORDER BY SUM(realized_pnl) DESC;"
echo "=== C2 our-copied distinct-decision WR post-epoch: wh|decisions|dec_w|dec_wr|net ==="
$RO "WITH d AS (SELECT $JN wh, condition_id, outcome_bet, SUM(realized_pnl) pnl FROM polymarket_round_trips WHERE division='polymarket_copy_trading' AND $EP AND $JW IN $R GROUP BY wh, condition_id, outcome_bet) SELECT wh||'|'||COUNT(*)||'|'||SUM(CASE WHEN pnl>0 THEN 1 ELSE 0 END)||'|'||ROUND(1.0*SUM(CASE WHEN pnl>0 THEN 1 ELSE 0 END)/COUNT(*),3)||'|'||ROUND(SUM(pnl),2) FROM d GROUP BY wh ORDER BY SUM(pnl) DESC;"
echo "=== C3 our-copied LAST-7d per-whale: wh|fills|mkts|net|last_entry ==="
$RO "SELECT $JN||'|'||COUNT(*)||'|'||COUNT(DISTINCT condition_id)||'|'||ROUND(SUM(realized_pnl),2)||'|'||substr(MAX(entry_ts),1,10) FROM polymarket_round_trips WHERE division='polymarket_copy_trading' AND entry_ts>=datetime('now','-7 days') AND $JW IN $R GROUP BY $JN ORDER BY SUM(realized_pnl) DESC;"
echo "=== C3b our-copied LAST-7d RESOLVED per-whale: wh|n|net ==="
$RO "SELECT $JN||'|'||COUNT(*)||'|'||ROUND(SUM(realized_pnl),2) FROM polymarket_round_trips WHERE division='polymarket_copy_trading' AND resolved_ts>=datetime('now','-7 days') AND $JW IN $R GROUP BY $JN ORDER BY SUM(realized_pnl) DESC;"
echo "=== C4 our-copied FULL-history per-whale: wh|n|net|first|last ==="
$RO "SELECT $JN||'|'||COUNT(*)||'|'||ROUND(SUM(realized_pnl),2)||'|'||substr(MIN(entry_ts),1,10)||'|'||substr(MAX(entry_ts),1,10) FROM polymarket_round_trips WHERE division='polymarket_copy_trading' AND $JW IN $R GROUP BY $JN ORDER BY SUM(realized_pnl) DESC;"
echo "=== C5 roster aggregate post-epoch: total_net|total_notional|roi% ==="
$RO "SELECT ROUND(SUM(realized_pnl),2)||'|'||ROUND(SUM(notional),2)||'|'||ROUND(100.0*SUM(realized_pnl)/SUM(notional),3) FROM polymarket_round_trips WHERE division='polymarket_copy_trading' AND $EP AND $JW IN $R;"
echo "=== C6 our-copied monthly per-whale: wh|mo|n|net ==="
$RO "SELECT $JN||'|'||substr(entry_ts,1,7)||'|'||COUNT(*)||'|'||ROUND(SUM(realized_pnl),2) FROM polymarket_round_trips WHERE division='polymarket_copy_trading' AND $EP AND $JW IN $R GROUP BY $JN, substr(entry_ts,1,7) ORDER BY $JN, substr(entry_ts,1,7);"
echo "=== C7 roster last-7d aggregate: n_entries|n_resolved|net_resolved ==="
$RO "SELECT (SELECT COUNT(*) FROM polymarket_round_trips WHERE division='polymarket_copy_trading' AND entry_ts>=datetime('now','-7 days') AND $JW IN $R)||'|'||(SELECT COUNT(*) FROM polymarket_round_trips WHERE division='polymarket_copy_trading' AND resolved_ts>=datetime('now','-7 days') AND $JW IN $R)||'|'||(SELECT ROUND(SUM(realized_pnl),2) FROM polymarket_round_trips WHERE division='polymarket_copy_trading' AND resolved_ts>=datetime('now','-7 days') AND $JW IN $R);"
echo "=== C8 whales in DB but NOT in current roster (recently-cut, last 21d activity): wh|wallet|last_entry|n ==="
$RO "SELECT $JN||'|'||$JW||'|'||substr(MAX(entry_ts),1,10)||'|'||COUNT(*) FROM polymarket_round_trips WHERE division='polymarket_copy_trading' AND $JW NOT IN $R AND entry_ts>='2026-07-20' GROUP BY $JW ORDER BY MAX(entry_ts) DESC LIMIT 25;"
echo "=== DONE ==="
