set -u
DB=/home/azureuser/trading_corp/data/trading_corp.db
RO="sqlite3 -readonly $DB"
echo "=== 0. prod clock (UTC) ==="
date -u +"%Y-%m-%dT%H:%M:%SZ"
echo "=== 1. kalshi_copy_trader kind breakdown, last 3 days ==="
$RO "SELECT kind, COUNT(*) n, MIN(ts) first, MAX(ts) last FROM audit_event WHERE actor='kalshi_copy_trader' AND ts>=datetime('now','-3 days') GROUP BY kind ORDER BY n DESC;"
echo "=== 2. ALL feed_anomaly rows last 3 days (ts + raw payload) ==="
$RO "SELECT ts, payload_json FROM audit_event WHERE actor='kalshi_copy_trader' AND kind='kalshi_copy_feed_anomaly' AND ts>=datetime('now','-3 days') ORDER BY ts;"
echo "=== 3. feed_anomaly earliest+latest+count last 3 days ==="
$RO "SELECT COUNT(*) n, MIN(ts) first_event, MAX(ts) last_event FROM audit_event WHERE actor='kalshi_copy_trader' AND kind='kalshi_copy_feed_anomaly' AND ts>=datetime('now','-3 days');"
echo "=== 4. selected_whales roster (raw) ==="
$RO "SELECT value_json FROM agent_state WHERE agent='kalshi_copy_trader' AND key='selected_whales';"
echo "=== 5. per-whale snapshot: key, position-count, updated_ts (FROZEN vs FRESH tell) ==="
$RO "SELECT key, (SELECT COUNT(*) FROM json_each(value_json)) n_positions, updated_ts FROM agent_state WHERE agent='kalshi_copy_trader' AND key LIKE 'positions:%' ORDER BY updated_ts;"
echo "=== 6. last_poll_ts (raw) ==="
$RO "SELECT value_json, updated_ts FROM agent_state WHERE agent='kalshi_copy_trader' AND key='last_poll_ts';"
echo "=== 7. full snapshot value_json for every tracked whale (what each holds) ==="
$RO "SELECT key, value_json FROM agent_state WHERE agent='kalshi_copy_trader' AND key LIKE 'positions:%' ORDER BY key;"
echo "=== 8. any NON-Maggie feed_anomaly last 3 days? (whale-scope check via LIKE) ==="
$RO "SELECT ts, payload_json FROM audit_event WHERE actor='kalshi_copy_trader' AND kind='kalshi_copy_feed_anomaly' AND ts>=datetime('now','-3 days') AND payload_json NOT LIKE '%Maggie%' ORDER BY ts;"
echo "=== DONE km1 ==="
