"""MACE economic-event calendar — read/write + idempotent seeds.

`economic_event` is the blackout source of truth (plan § Entry pipeline
filter 4). Rows carry four provenances:

  - 'seed'   : FOMC/CPI/NFP imported from config/macro_calendar.yaml. T12:
               that YAML stays master; the weekly loop re-seeds idempotently.
  - 'rule'   : LPR-fix rows generated by the 20th-of-month rule (weekend-rolled).
  - 'manual' : operator-supplied OPEC+/Copom/BR-election/politburo dates (CLI).
  - 'feed'   : reserved for a future EODHD/FMP feed (deferred post-launch;
               OQ-1 launches on manual+seed+rule).

This module is PURE calendar I/O — it does NOT decide blackouts. The
entry-pipeline match (event_type in the symbol's blackout_event_types AND
symbol_scope in {'ALL', symbol} AND date in {today, next session}) lives in
strategy.py (Phase 2). Idempotency rides on the table's
UNIQUE(event_type, event_date, symbol_scope): every writer uses
INSERT OR IGNORE, so weekly re-seeds never duplicate.

`symbol_scope` convention: 'ALL' means market/region-wide (the per-symbol
blackout_event_types list is what actually scopes which symbols honor the
event). Region-specific events MAY be pinned to a symbol via the CLI.
"""
from __future__ import annotations

import sqlite3
from datetime import date, timedelta
from pathlib import Path

import yaml

from trading_corp.utils.time import now_utc, to_et

SCOPE_ALL = "ALL"

SOURCE_SEED = "seed"
SOURCE_RULE = "rule"
SOURCE_MANUAL = "manual"
SOURCE_FEED = "feed"
SOURCES = frozenset({SOURCE_SEED, SOURCE_RULE, SOURCE_MANUAL, SOURCE_FEED})

# macro_calendar.yaml event types MACE recognizes as blackout seeds. FOMC/CPI
# are the launch need (SPY/TLT blackout lists); NFP is co-imported because it
# is a genuine macro event already in the YAML — inert unless a symbol lists it.
_SEED_EVENT_TYPES = ("FOMC", "CPI", "NFP")

# LPR (Loan Prime Rate) is fixed by the PBOC on the 20th of each month
# (Beijing morning). Only FXI lists LPR_FIX today. event_date is the China
# fixing date; the ET-session offset is a deliberate simplification (FXI is
# disabled until the gated expansion, and the blackout window spans
# today-OR-next-session anyway). Weekend roll only — China public holidays are
# NOT modeled; the operator overrides a holiday-shifted month via the CLI.
LPR_EVENT_TYPE = "LPR_FIX"
_LPR_DAY_OF_MONTH = 20


# ── helpers ─────────────────────────────────────────────────────────────

def _norm(s: str) -> str:
    return str(s).strip().upper()


def _as_iso_date(d: date | str) -> str:
    if isinstance(d, date):
        return d.isoformat()
    # accept 'YYYY-MM-DD' (validate)
    return date.fromisoformat(str(d)).isoformat()


def _classify_macro(name: str) -> str | None:
    """Map a macro_calendar.yaml event name to a MACE event_type, or None."""
    up = (name or "").upper()
    if "FOMC" in up:
        return "FOMC"
    if "CPI" in up:
        return "CPI"
    if "NFP" in up or "EMPLOYMENT SITUATION" in up:
        return "NFP"
    return None


def _macro_ts_to_et_date(raw_ts) -> date | None:
    """config/macro_calendar.yaml ts is UTC (str or naive/aware datetime) ->
    ET calendar date (the session the US market reacts on). `to_et` handles
    both input types and assumes UTC for naive values."""
    et = to_et(raw_ts)
    return et.date() if et else None


def _roll_weekend_forward(d: date) -> date:
    """Sat -> Mon, Sun -> Mon. Weekdays unchanged. (Holidays not modeled.)"""
    wd = d.weekday()  # 0=Mon .. 6=Sun
    if wd == 5:
        return d + timedelta(days=2)
    if wd == 6:
        return d + timedelta(days=1)
    return d


# ── write primitives ────────────────────────────────────────────────────

def add_event(
    conn: sqlite3.Connection,
    *,
    event_type: str,
    event_date: date | str,
    source: str,
    symbol_scope: str = SCOPE_ALL,
    fetched_at: str | None = None,
) -> bool:
    """Insert one economic_event row (INSERT OR IGNORE — idempotent on the
    UNIQUE key). Returns True iff a new row was written. Does not commit;
    autocommit connections (db.connect) persist immediately, tests read back
    on the same connection.
    """
    if source not in SOURCES:
        raise ValueError(f"source {source!r} not in {sorted(SOURCES)}")
    et = _norm(event_type)
    if not et:
        raise ValueError("event_type must be non-empty")
    ed = _as_iso_date(event_date)
    scope = _norm(symbol_scope) or SCOPE_ALL
    fa = fetched_at or now_utc().isoformat(timespec="seconds")
    cur = conn.execute(
        "INSERT OR IGNORE INTO economic_event "
        "(event_type, symbol_scope, event_date, source, fetched_at) "
        "VALUES (?, ?, ?, ?, ?)",
        (et, scope, ed, source, fa),
    )
    return cur.rowcount > 0


def remove_event(
    conn: sqlite3.Connection,
    *,
    event_type: str,
    event_date: date | str,
    symbol_scope: str = SCOPE_ALL,
) -> int:
    """Delete matching rows. Returns the number removed."""
    cur = conn.execute(
        "DELETE FROM economic_event "
        "WHERE event_type = ? AND event_date = ? AND symbol_scope = ?",
        (_norm(event_type), _as_iso_date(event_date), _norm(symbol_scope) or SCOPE_ALL),
    )
    return cur.rowcount


def list_events(
    conn: sqlite3.Connection,
    *,
    start: date | str | None = None,
    end: date | str | None = None,
    event_type: str | None = None,
    source: str | None = None,
    symbol_scope: str | None = None,
) -> list[dict]:
    """Return economic_event rows (as dicts) ordered by (event_date, event_type),
    filtered by the optional bounds/facets."""
    where: list[str] = []
    params: list = []
    if start is not None:
        where.append("event_date >= ?"); params.append(_as_iso_date(start))
    if end is not None:
        where.append("event_date <= ?"); params.append(_as_iso_date(end))
    if event_type is not None:
        where.append("event_type = ?"); params.append(_norm(event_type))
    if source is not None:
        where.append("source = ?"); params.append(str(source))
    if symbol_scope is not None:
        where.append("symbol_scope = ?"); params.append(_norm(symbol_scope) or SCOPE_ALL)
    sql = "SELECT id, event_type, symbol_scope, event_date, source, fetched_at FROM economic_event"
    if where:
        sql += " WHERE " + " AND ".join(where)
    sql += " ORDER BY event_date, event_type"
    return [dict(r) for r in conn.execute(sql, params).fetchall()]


# ── seeds ────────────────────────────────────────────────────────────────

def seed_from_macro_calendar(
    conn: sqlite3.Connection,
    macro_path: str | Path = "config/macro_calendar.yaml",
    *,
    event_types: tuple[str, ...] = _SEED_EVENT_TYPES,
    fetched_at: str | None = None,
) -> dict:
    """Import FOMC/CPI/NFP from macro_calendar.yaml as source='seed' rows,
    symbol_scope='ALL'. Idempotent (INSERT OR IGNORE). T12: the YAML stays
    master; this only mirrors it into the query surface. Returns a report."""
    p = Path(macro_path)
    allowed = {_norm(t) for t in event_types}
    inserted = 0
    skipped = 0
    unclassified = 0
    by_type: dict[str, int] = {}
    try:
        data = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    except FileNotFoundError:
        return {"inserted": 0, "skipped": 0, "unclassified": 0, "by_type": {},
                "error": f"macro calendar not found: {p}"}
    for ev in (data.get("events") or []):
        etype = _classify_macro(str(ev.get("name", "")))
        if etype is None or etype not in allowed:
            if etype is None:
                unclassified += 1
            continue
        ed = _macro_ts_to_et_date(ev.get("ts"))
        if ed is None:
            unclassified += 1
            continue
        if add_event(conn, event_type=etype, event_date=ed, source=SOURCE_SEED,
                     symbol_scope=SCOPE_ALL, fetched_at=fetched_at):
            inserted += 1
            by_type[etype] = by_type.get(etype, 0) + 1
        else:
            skipped += 1
    return {"inserted": inserted, "skipped": skipped,
            "unclassified": unclassified, "by_type": by_type}


def generate_lpr_fix_rule(
    conn: sqlite3.Connection,
    *,
    today: date | None = None,
    months: int = 13,
    symbol_scope: str = SCOPE_ALL,
    fetched_at: str | None = None,
) -> dict:
    """Generate LPR_FIX rows (source='rule') on the 20th of each month for
    `months` consecutive months starting with the current month, weekend-rolled
    to the next business day. Idempotent. Returns a report incl. the dates."""
    base = today or to_et(now_utc()).date()
    inserted = 0
    skipped = 0
    dates: list[str] = []
    y, m = base.year, base.month
    for i in range(months):
        yy = y + (m - 1 + i) // 12
        mm = (m - 1 + i) % 12 + 1
        d = _roll_weekend_forward(date(yy, mm, _LPR_DAY_OF_MONTH))
        iso = d.isoformat()
        dates.append(iso)
        if add_event(conn, event_type=LPR_EVENT_TYPE, event_date=d,
                     source=SOURCE_RULE, symbol_scope=symbol_scope,
                     fetched_at=fetched_at):
            inserted += 1
        else:
            skipped += 1
    return {"inserted": inserted, "skipped": skipped, "dates": dates}


def weekly_refresh(
    conn: sqlite3.Connection,
    macro_path: str | Path = "config/macro_calendar.yaml",
    *,
    today: date | None = None,
    lpr_months: int = 13,
    fetched_at: str | None = None,
) -> dict:
    """Idempotent weekly refresh: re-seed FOMC/CPI/NFP + regenerate the LPR
    rule horizon. Wired into the Phase-4 weekly calendar-refresh loop; also the
    CLI `refresh` command. Manual rows are untouched (never regenerated)."""
    seed = seed_from_macro_calendar(conn, macro_path, fetched_at=fetched_at)
    lpr = generate_lpr_fix_rule(conn, today=today, months=lpr_months,
                                fetched_at=fetched_at)
    return {"seed": seed, "lpr": lpr}
