# bootsmoke.ps1 - post-restart gate 3 (read-only). Verifies the bidirectional SFP deploy
# booted healthy. Operator paste: powershell -ep bypass -f .\bootsmoke.ps1
$ErrorActionPreference = "Stop"
$H = "azureuser@trading.jacksumner.com"
Write-Host "=== BOOT-SMOKE (gate 3) ==="
$cmd = @'
cd /home/azureuser/trading_corp; boot=$(systemctl show trading-corp -p ActiveEnterTimestamp --value); echo "PID=$(systemctl show trading-corp -p MainPID --value) NRestarts=$(systemctl show trading-corp -p NRestarts --value) state=$(systemctl show trading-corp -p ActiveState --value)/$(systemctl show trading-corp -p SubState --value) boot=$boot"; echo "== tracebacks since boot (want 0) =="; sudo -n journalctl -u trading-corp --since "$boot" --no-pager 2>/dev/null | grep -icE "traceback|error|exception"; echo "== BOTH divisions reconcile at startup =="; sudo -n journalctl -u trading-corp --since "$boot" --no-pager 2>/dev/null | grep -iE "reconciler .bitunix_(sfp|futures). at startup"; echo "== regime seed depth per coin (want >=800) =="; for c in BTC ETH SOL XRP; do sudo -n journalctl -u trading-corp --since "$boot" --no-pager 2>/dev/null | grep -iE "regime seed ${c}USDT" | tail -1; done; echo "== 3 new tables exist =="; sqlite3 data/trading_corp.db "SELECT name FROM sqlite_master WHERE type='table' AND name IN ('bitunix_sfp_research_log','bitunix_sfp_regime_flip','bitunix_sfp_regime_state') ORDER BY name"; echo "== regime-state mirror: current regime per coin (want 4 rows once warmed) =="; sqlite3 data/trading_corp.db "SELECT coin,regime,updated_ts FROM bitunix_sfp_regime_state ORDER BY coin"; echo "== flip-watch rows so far =="; sqlite3 data/trading_corp.db "SELECT COUNT(*) FROM bitunix_sfp_regime_flip"; echo "== kill-switch value (want side: regime) =="; grep -E "^  side:" config/strategies.yaml; echo "== SFP armed universe (symbol_modes) =="; sed -n "/^bitunix_sfp:/,/^[a-zA-Z]/p" config/strategies.yaml | grep -E "USDT.P.: \{ bos_tf"
'@
$cmd | ssh $H "tr -d '\r'|bash"
Write-Host "=== ALL GREEN if: 0 tracebacks ; BOTH reconcilers clean ; regime seed >=800 x4 coins ; 3 tables ; regime-state x4 (post-warmup) ; side: regime ; 4 symbol_modes armed. THEN -> First-live A/B (RUNBOOK). ==="
